name: vin_scanner
description: '''A customizable Flutter widget for barcode scanning. Supports orientation lock, resolution presets, overlay styling, and configurable frame processing rate.'''
version: 0.0.5
homepage: https://github.com/flutter-devs/vin_scanner.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.3
  google_mlkit_barcode_scanning: ^0.14.0
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter: